language: node_js

os:
  - linux

node_js:
  - "8"
  - "node" # latest stable Node.js release

script:
  - npm run test
  - npm run build

notifications:
  email:
    on_success: never
    on_failure: always
